export function generateCategories() {
  return [
    { name: "Live Music" },
    { name: "Comedy" },
    { name: "Art" },
    { name: "Sports" },
    { name: "Technology" },
    { name: "Education" },
    { name: "Food and Drink" },
    { name: "Networking" },
    { name: "Health and Wellness" },
    { name: "Fashion" },
    { name: "Music Festival" },
    { name: "Conference" },
    { name: "Workshop" },
    { name: "Theater" },
    { name: "Dance" },
    { name: "Film" },
    { name: "Literature" },
    { name: "Outdoor Activities" },
    { name: "Gaming" },
    { name: "Charity" },
    { name: "Community" },
  ];
}
